ALTER TABLE projects ADD COLUMN IF NOT EXISTS broker_email VARCHAR(255);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS broker_phone VARCHAR(50);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS broker_company VARCHAR(255);
